kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: kratos-layout
namespace: taskon-dev
configMapGenerator:
  - name: kratos-layout
generatorOptions:
  disableNameSuffixHash: true
resources:
  - deployment.yaml
  - service.yaml
