kind: Service
apiVersion: v1
metadata:
  name: kratos-layout
  namespace: taskon-dev
spec:
  ports:
    - name: http-server
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: grpc-server
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: portal
      port: 20000
      protocol: TCP
      targetPort: 20000
  selector:
    app: kratos-layout
  type: NodePort
