// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v4.25.1
// source: example/portal.proto

package example

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPortalnothing = "/example.Portal/nothing"

type PortalHTTPServer interface {
	Nothing(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

func RegisterPortalHTTPServer(s *http.Server, srv PortalHTTPServer) {
	r := s.Route("/")
	r.GET("/portal/nothing", _Portal_Nothing0_HTTP_Handler(srv))
}

func _Portal_Nothing0_HTTP_Handler(srv PortalHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortalnothing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Nothing(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type PortalHTTPClient interface {
	Nothing(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type PortalHTTPClientImpl struct {
	cc *http.Client
}

func NewPortalHTTPClient(client *http.Client) PortalHTTPClient {
	return &PortalHTTPClientImpl{client}
}

func (c *PortalHTTPClientImpl) Nothing(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/portal/nothing"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPortalnothing))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
